### ISSUE TITLE
[Feature Request] 'Compact add-on manager view' option for 'FT Deepdark' complete theme

### ISSUE THREAD

**Issue by MacgyverJohnson** [Aris-t2/ClassicThemeRestorer#224]
Hello @Aris-t2  
**Thanks** for the amazing addon CTR..since firefox 44 I have been using it and loved it ......totally amazing that u added compatibility with omnisidebar and other addons

Would u kindly add support for firefox's most popular theme FT Deepdark...addon page compact view is not affecting somehow when that theme is enabled.....
TIA

**Comment by Aris-t2** [comment]
I think you found a bug. The "compact view for add-ons page" options should not be visible for complete themes. In fact the main option is hidden, just the sub option "compact view+" is yet visible.

For those settings to work properly some parts of add-ons manager theme have to be modified. I can do this for the "default themes", but nor for "complete themes" where every theme handles code differently.

Here is the code CTR uses. Add it to a Stylish style to see its results:

```css
@-moz-document url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons) {

	/* dimensions / positioning */
	#addons-page .main-content{
	  padding: 0 !important;
	  margin: 0 !important;
	}
	
	#addons-page #header-search .textbox-input-box{
	  height: 18px !important;
	}
	
	#addons-page #addon-list {
	  -moz-margin-start: -1px !important;
	}
	.addon{
	  padding-top: unset !important;
	  padding-bottom: unset !important;
	}
	#addons-page #detail-view,
	#addons-page #userstyle-sorting,
	#addons-page .global-warning-container,
	#addons-page .global-info-container{
	  -moz-margin-start: 0px !important;
	  -moz-margin-end: 1px !important;
	}

	#addons-page .detail-view-container {
	  -moz-margin-start: 10px !important;
	}

	#addons-page #view-port{
	  -moz-margin-end: 4px !important;
	}

	#addons-page #header{
	  padding: 2px 0 !important;
	  margin: 0 !important;
	}

	/* buttons / menulists */
	#addons-page #header button,
	#addons-page #header #header-utils-btn,
	#addons-page #list-view .global-info button,
	#addons-page #list-view .discover-button,
	#addons-page .status-control-wrapper button,
	#addons-page #userstyle-sorting button,
	#addons-page #update-actions button,
	#addons-page #updates-list-empty button,
	#addons-page .relnotes-toggle,
	#list-view menulist{
	  padding:2px !important;
	  min-height: unset !important;
	  height: unset !important;
	  font-size: 90% !important;
	}

	#addons-page #header-utils-btn{
	  padding: 2px !important;
	  height: unset !important;
	}

	#addons-page button.sorter{
	  padding:2px !important;
	  min-height: 26px !important;
	  height: unset !important;
	}

	#addons-page #header-search{
	  padding: 1px !important;
	  min-height: unset !important;
	  height: unset !important;
	}
	
	#addons-page .addon .name-container,
	#addons-page #addon-list .name-container {
	  font-size: 130% !important;
	}
	.sort-controls,
	#addons-page #addon-list .warning,
	#addons-page #addon-list .pending,
	#addons-page #addon-list .error{
	  font-size: 90% !important;
	}
	
	button.addon-control image{
	  margin-top: -1.5px !important;
	  margin-bottom: -1.5px !important;
	}

	/* search */
	#search-filter {
	  font-size: 90% !important;
	}

	/* detail view */
	#detail-view button:not(.button-link):not(.text-link),
	#detail-view menulist{
	  padding:2px !important;
	  height: unset !important;
	  font-size: 90% !important;
	  background-image: linear-gradient(to bottom, rgba(255,255,255,0.15), rgba(255,255,255,0.20),rgba(0,0,0,0.01)) !important;
	}
	
	#detail-view colorpicker[type="button"]{
	  padding:2px !important;
	  min-height: 26px !important;
	  min-width: 40px !important;
	  height:auto !important;
	  width: auto !important;
	}
	
	#detail-view label{
	  font-size: 90% !important;
	}

	#detail-view .creator-link{
	  font-size: 110% !important;
	}
	
	/* checkbox and radio items */
	#addons-page checkbox image,
	#addons-page radio image {
	  width: 16px !important;
	  height: 16px !important;
	  margin: 0 !important;
	}

	/********************/
	.addon .warning,
	.addon .error,
	.addon .pending,
	.addon .icon-container {
	  padding: unset !important;
	  margin: unset !important;
	  min-width: unset !important;
	  width: unset !important;
	  min-height: unset !important;
	  height: unset !important;
	}

	.addon .icon {
	  min-width: unset !important;
	  min-height: unset !important;
	  width: 21px !important;
	  height: 21px !important;
	}
	
	.addon .warning-icon,
	.addon .error-icon,
	.addon .pending-icon {
	  width: 14px !important;
	  height: 14px !important;
	  -moz-margin-start: 4px !important;
	}

	.addon .content-inner-container{
	  -moz-box-orient: horizontal !important;
	}
	#updates-list .addon .content-inner-container{
	  -moz-box-orient: vertical !important;
	}

	.addon .name-container .name,
	.addon .name-container .version,
	.addon .name-container .disabled-postfix,
	.addon .name-container .update-postfix {
	  font-size:85% !important;
	  -moz-margin-start: 4px !important;
	  -moz-margin-end: 0 !important;
	}
	
	.addon .content-container * {
	  font-size: 100% !important;
	}

	.addon .update-available button,
	.addon .control-container button,
	.addon .control-container menulist {
	  margin-top: 1px !important;
	  margin-bottom: 1px !important;
	  -moz-margin-start: 1px !important;
	  -moz-margin-end: 0px !important;
	}
	
	.addon .warning .button-box,
	.addon .pending .button-box,
	.addon .content-inner-container,
	.addon .description-container .button-link,
	.addon .update-available .button-box,
	.addon .control-container .button-box,
	.addon .control-container menulist .menulist-label-box {
	  padding: unset !important;
	  margin: unset !important;
	}

	.description-container spacer {
	  display: none !important;
	}

	.description-container .button-link .button-box {
	  -moz-padding-start: 0px !important;
	  -moz-padding-end: 2px !important;
	}

}
```
