### ISSUE TITLE
Squared tabs & overflow mode: gap between last tab and tab scroll button ">"

### ISSUE THREAD

**Issue by q1k** [Aris-t2/ClassicThemeRestorer#237]
There is extra space on the tab bar when scrolling is activated, so when moving tabs around you can drop them either before or after that.
After moving the tab the space is still there at the end.
![Extra space at the end of the tab](https://s31.postimg.org/d4suv0e23/image.png)

Scrolling all the way to the first tab hides this extra space.

**Comment by Aris-t2** [comment]
Unfortunately that is not a bug, but correct behavior (-> see curved default tabs) in Fx29+.
If you scroll to the right, you see that space is used by tabs. Changing anything there breaks tabs ui.

**Comment by q1k** [comment]
Thanks for the info.
BTW, is there no way to reduce that space to be 0?

**Comment by Aris-t2** [comment]
There are some cases where this code will break the ui, but using this in Stylish does the trick.
```css
/*AGENT_SHEET*/
#tabbrowser-tabs[overflow] tab[last-tab="true"][last-visible-tab="true"] {
  -moz-margin-end: -15px !important;
}
```
Please report all cases you can find, where this code breaks the ui.

**Comment by q1k** [comment]
Well when moving a tab to the last position, reveals that extra space again.


Also I noticed that when opening a new tab, the tab goes briefly on top of the other buttons. This also happens even without the code above.
![](https://s32.postimg.org/dv9r1b4hh/image.png)

**Comment by Aris-t2** [comment]
Well, I did say the code will cause issues and not work perfectly. There is a reason why it is not part of CTR ;-)

The second issue is related to Mozillas crappy 'tab opening animation'. You can disable it on CTRs options window (last category), if you don't like the short tab overlapping animation.

**Comment by q1k** [comment]
That code seems to do the trick, I will be using it and will report if I notice anything out of order.

<br>
As for the tab opening animation, I have a question.
-Is it possible to only disable the tab opening animation and not the closing?
-And is it possible to make the tab open/close animation faster?

**Comment by Aris-t2** [comment]
I don't know, if it is possible to seperate them. The option is just a switch to what Firefox offers.

You can change general open/close duration with this code by altering the values:
```css
#tabbrowser-tabs,
#tabbrowser-tabs *,
.tabbrowser-tab,
.tabbrowser-tab * {
  transition: 0.01s !important;
  transition-duration: 0.01s !important;
}
```

**Comment by q1k** [comment]
Thanks,
I have added
```
transition: 0.1s !important;
transition-duration: 0.1s !important;
```

**Comment by q1k** [comment]
OK, so apart from the transition problem, which can be solved with removing <code>transition: 0.1s !important;</code>,
The other thing with the -15px margin, when going out of fullscreen (I have tested only with a youtube video so far.), the tab is behind the scroll button [>]

**Comment by Aris-t2** [comment]
I think you now have your answer why removing the gap between last tab and tab scrollers has to stay.

My guess is keeping focus on selected tab is a feature when switching between screen modes. If I'm not wrong, Firefox redraws the window everytime you enter or leave a mode (normal, maximized, fullscreen). That is what caused the tab behavior your are speaking of.

**Comment by q1k** [comment]
Well, I can't test at the moment for the different sizes of the window.
But what I actually meant was, going full-screen on a video and out, it scrolls the bar to get the current tab into view.

**Comment by Aris-t2** [comment]
I understand, but "auto scrolling back to active tab after leaving full screen mode" is really a browser feature and has nothing to do with CTR or the given code.

----

The overlapping you described is indeed there ( #tabbrowser-tabs[overflow] tab**[last-tab="true"]** ) and I have no explanation for what Mozilla is doing there. The tag "last-tab" is actually not exclusively used by the last tab, but also added to every _new_ last tab. 
e.g. 10 tabs + tab scroll buttons visible > 10s tab gets "last tab" tag > open two more tabs and 12s tab gets "last tab" tag too, but 10s tab still keeps it for whatever reasons. So the code to remove the gap was doomed from the start.

However I could not reproduce the overlapping with this code (also posted above), where **[last-visible-tab="true"]** tag is really only added to the last tab, but you mentioned another glitch with it, right?
```css
#tabbrowser-tabs[overflow] tab[last-visible-tab="true"]{
  -moz-margin-end: -15px !important;
}
```

Disabling the tab opening and closing animations via css was more an experiment. It has too many ugly sideeffects. I would recommend to use browsers default preference **browser.tabs.anaimate>false** for the time it is there. CTR offers a switch for it.

If you like to experiment with css, then changing the given code to this will fix the glitch you experienced when moving tabs.
```css
#tabbrowser-tabs:not([movingtab="true"]),
#tabbrowser-tabs:not([movingtab="true"]) *,
#tabbrowser-tabs:not([movingtab="true"]) .tabbrowser-tab,
#tabbrowser-tabs:not([movingtab="true"]) .tabbrowser-tab * {
  transition-duration: 0.00ms !important;
}
```
