### ISSUE TITLE
Pinned tabs stacking/overlapping

### ISSUE THREAD

**Issue by TheTopMostDog** [Aris-t2/ClassicThemeRestorer#260]
Checking `Tabs (1)`: `Remove empty favicon from pinned tabs` [[image](https://i.imgur.com/efC9KmW.png)] causes pinned tabs to appear to stack on program launch. [[image](https://i.imgur.com/Mhcgfiy.png)] 

This might be a side effect of relatively slow internet in Australia; icons are loading slow enough that the feature removes the space reserved for the icon prior to the icon loading, resulting in a bunch of icons loading on top one another. 

It can be resolved regardless by ensuring that the action occurs a short amount of time after startup (giving icons time to load), or by locking the width of pinned tabs (if extremely narrow tabs is not desired behaviour).

**Comment by Aris-t2** [comment]
Could you run some tests, so we can find a solution quicker?

CTRs option currently uses this code
```css
.tabbrowser-tab[pinned] .tab-text,
.tabbrowser-tab[pinned] .tab-icon-image:not([src]) {
  display:none !important;
}
```

Could you disable that option, install Stylish add-on, add these code snippets to a new Style each and report, if one or more of them work fine for you?
(only leave one of them enabled at once)
```css
.tabbrowser-tab[pinned] .tab-text,
.tabbrowser-tab[pinned] .tab-icon-image:not([src]) {
   visibility: collapse !important;
}
```
```css
.tabbrowser-tab[pinned] .tab-icon-image:not([src]) {
   visibility: hidden !important;
}
.tabbrowser-tab[pinned] .tab-text {
  display:none !important;
}
```
```css
.tabbrowser-tab[pinned] .tab-icon-image:not([src]) {
   display:none !important;
}
.tabbrowser-tab[pinned] .tab-text {
  visibility: hidden !important;
}
```
