### ISSUE TITLE
Remove anti-cascading file menu margins

### ISSUE THREAD

**Issue by jabcreations** [Aris-t2/ClassicThemeRestorer#321]
There is a `margin-bottom` and `margin-top` of 3px on the file menu that I can neither override via `userChrome.css` nor was I able to fix the XPI file manually to continue fixing the theme.

chrome://ctraddon_os_special/skin/tabsontop_offextra.css

The selector appears three freaking times! It needs to be outright ripped out or if you really absolutely want to have it then you need to implement an option so it can be disabled or have it's value set to 0.

```
#main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar
 {
 margin-top: 3px !important;
 margin-bottom: 3px !important;
 }
```

I've confirmed it is that file, I think it's _content\css\winaero\tabsontop_offextra.css_ though I'm not certain which one is being used for Windows 7.

Frankly the OS themes need to be implemented as themes by Mozilla, not force-fed in to the code itself! It's been exceptionally frustrating trying to clean up the GUI because of so much trash code on Mozilla's part and therefore the extra code by each dev to achieve a goal on top of given whatever.

**Comment by Aris-t2** [comment]
I'm sure you have a proper reason to see those values as insufficient for your configuration, but CTR has to take care of many different cases and OS themes. Changing one value might look fine on one configuration, but can cause another configuration to break.

It is not a secret userChrome.css is useless when it comes to override CTRs style sheets. Both use different levels to apply css code and userChrome.css uses the weaker one in this case.

![1](https://cloud.githubusercontent.com/assets/6013569/22416337/3ea3bf48-e6ce-11e6-8084-f022b3562260.png)
![2](https://cloud.githubusercontent.com/assets/6013569/22416338/3ea63e76-e6ce-11e6-8b1f-d39fde91a6ed.png)


CTR 1.6.1 offers a new option where you can add custom css, that actually is able to override CTRs code, if used correctly. Otherwise you would need Stylish with 
```css
/*AGENT_SHEET*/
 ````
in first line of the style.

```css
#main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar {
  margin-top: 0px !important;
  margin-bottom: 0px !important;
}
```

**Comment by jabcreations** [comment]
Ah, well this would have been nice to know about six hours ago! LoL... Thank you for the clarification. It seems pointless to not have userChrome.css be allowed to cascade over all the other CSS.

I'll take a look and see what I can manage. Thank you for the reply and for thinking of implementing the CSS override for the extension itself within the extension itself.

**Comment by Aris-t2** [comment]
"It seems pointless to not have userChrome.css be allowed to cascade over all the other CSS."

I agree, but userChrome.css registers style sheets on "user" level, while CTR already has to use "agent" level to override default Firefox code.

I think you see, why overriding something within userChrome.css on user level, that already got overridden on agent level is impossible. It is not just my decision to implement css like that. In most cases it is the only way to change some of Firefox areas properly.

**Comment by jabcreations** [comment]
So your code temporarily fixes the issue when using it in CTR's Custom CSS code textarea however after restarting the browser it doesn't take effect until _after_ I make any change (regardless of how trivial) to the CSS. Obviously it should take effect immediately like all of the other CSS code (which works fine as we both intended). I've pasted the CSS you provided and added it to the bottom, the top and to the very bottom of the `userChrome.css` file all without success.

On a more positive note I've been able to iron out all the issues I've come across otherwise with cleaning up the theme I'm working on.

**Comment by jabcreations** [comment]
I looked at chrome://ctraddon_os_special/skin/tabsontop_offextra.css more carefully and remembered that I had seen multiple instances. Well I updated the CSS in both the extension and the userChrome.css file and I'm still having the same problem I posted.

```
#main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar
{
 margin-top: 0px !important;
 margin-bottom: 0px !important;
}


@media all and (-moz-windows-compositor)
{
 #main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar
 {
  margin-top: 0px !important;
  margin-bottom: 0px !important;
 }
}

@media all and (-moz-windows-classic)
{
 #main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar
 {
  margin-top: 0px !important;
  margin-bottom: 0px !important;
}

```

**Comment by Aris-t2** [comment]
Lets make the code more powerful and see, if it will work after a restart too (it did for me):

```css
#main-window[tabsintitlebar]:not([inFullscreen]) #tab-view-deck #browser-panel #navigator-toolbox #toolbar-menubar {
  margin-top: 0px !important;
  margin-bottom: 0px !important;
}
```

**Comment by pkrabbit** [comment]
Your code did work after a restart/new window, how exactly did you make it more powerful? Would it be possible to make CTR reapply the CSS on new windows?

What I want to do is remove the radial gradient when hovering over the Firefox button, but it reverts on restarts/new windows:
```
#TabsToolbar #ctraddon_appbutton:hover:not(:active):not([open]),
#ctraddon_appbutton2:hover:not(:active):not([open]) {
	background-image: linear-gradient(rgb(255, 10, 10), rgb(192, 10, 10)) !important;
}
```

**Comment by Aris-t2** [comment]
By design the application has multiple layers, nodes and the root.

Simple example

> window
>> top box 
>>> top toolbars
>>>> top tolbar buttons

> window
>> bottom box
>>> bottom toolbars
>>>> bottom toolbar buttons

I hope you get the idea. Code is more powerful, if it uses higher node structure before the actual element.

"top toolbar buttons" {something} can be overridden by "top box > top toolbar buttons {something}" etc.

#main-window[tabsintitlebar]:not([inFullscreen]) #navigator-toolbox #toolbar-menubar
->
#main-window[tabsintitlebar]:not([inFullscreen]) **#tab-view-deck #browser-panel** #navigator-toolbox #toolbar-menubar

I have added more nodes to the previous code.

```css
#ctraddon_appbutton:hover:not(:active):not([open]),
#ctraddon_appbutton2:hover:not(:active):not([open]) {
  background-image: linear-gradient(rgb(255, 10, 10), rgb(192, 10, 10)) !important;
}
```

You have to add higher nodes to the code (untested example):
```css
#main-window toolbox toolbar #ctraddon_appbutton:hover:not(:active):not([open]),
#main-window #titlebar #titlebar-content #ctraddon_appbutton2:hover:not(:active):not([open]) {
  background-image: linear-gradient(rgb(255, 10, 10), rgb(192, 10, 10)) !important;
}
```

The easily find nodes I suggest to install "DOM Inspector" and "Element Inspector" add-ons. Then you just have to hold Shift key and right click any ui element you want to now stuff about. A new window opens listing all attributes. Hitting a button in top line above the rules on the right lets you switch to CSS for example where you can see code used by that item. 
On the left you have a tree structure where you see items hierarchy, nodes above it etc.
