### ISSUE TITLE
CSS specificity quite high

### ISSUE THREAD

**Issue by Ede123** [Aris-t2/ClassicThemeRestorer#33]
Hi Aris,

I noticed that the specificity of your CSS is quite high (so high that it is actually very hard to override in some cases):

* For once many of the rules are defined as `!important`.
* Furthermore you add your style sheets as `AGENT_SHEET`s which puts them always last and therefore with a higher specificity.
* Last but not least your selectors have quite high specificity to start with.

As a real world example I tried to override a ruleset in [smallnavbutextra.css](../blob/master/xpi/content/css/winaero/smallnavbutextra.css#L165).
In the end I had not only to add an overly specific selector but also make my style sheet an `AGENT_SHEET` as visible in Ede123/greasy-scripts@79cbdc99613f3c298d8a22ea51e9e1ae7091fd17

So while not exactly a bug or feature request, if you see a chance to lower specificity of some of your CSS it would probably increase compatibility with other add-ons a lot. It's already hard enough to test on all platforms, so it would benefit all parties involved.
(Actually, if nobody made me aware of this issue it would have gone unnoticed, which I assume happens a lot already and is bad for everyone).

Regards,
Eduard

**Comment by InternalError503** [comment]
Maybe changing how the css is implemented allowing for a global override if needed.

Take this for an example:

```css
:root {
	--ctr-moz-appearance: none;
	--ctr-background: none;
	--ctr-background-image: none;
	--ctr-border-radius: 2.5px;
	--ctr-border-color: transparent;
	--ctr-box-shadow: none;
	--ctr-transition-property: none;
	--ctr-transition-duration: 0ms;
}

#navigator-toolbox #nav-bar #back-button[disabled] > .toolbarbutton-icon,
#navigator-toolbox #nav-bar .toolbarbutton-menubutton-dropmarker > image,
#navigator-toolbox #nav-bar .toolbarbutton-menubutton-button .toolbarbutton-icon,
#navigator-toolbox #nav-bar toolbarbutton[type="menu-button"] > .toolbarbutton-icon,
#navigator-toolbox #nav-bar .toolbarbutton-1:-moz-any(:hover ,[checked],[open],[type="menu-button"]) > .toolbarbutton-icon,
#navigator-toolbox #nav-bar .toolbarbutton-1[type="menu-button"] > .toolbarbutton-menubutton-dropmarker::before{
	-moz-appearance: var(--ctr-moz-appearance)!important;
	background: var(--ctr-background)!important;
	background-image: var(--ctr-background-image)!important;
	border-radius: var(--ctr-border-radius)!important;
	border-color: var(--ctr-border-color)!important;
	box-shadow: var(--ctr-box-shadow)!important;
	transition-property: var(--ctr-transition-property)!important;
    transition-duration: var(--ctr-transition-duration)!important;
}
```

Here they still use the `!important` so they will override top level but if someone needs to override one or more of these settings they can target like in this example.

```css
:root {
	--ctr-border-radius: 16px !important;
}
```

On the new selector in the `:root` they just target it with a new value and `!important` which will make it top level.

I am currently using this in cyberCTR with home page css, I am sure something like this could be reworked to suit.
