### ISSUE TITLE
How to hide "Search Glass" on OLD search bar ?

### ISSUE THREAD

**Issue by GitCurious** [Aris-t2/ClassicThemeRestorer#343]
I have tried some css snippets but can not find a way to hide the magnifying glass icon, ie: the "search glass" on the OLD style search bar.

Is this possible to do ?

**Comment by Aris-t2** [comment]
Removing the search glass completely with "visibility: collapse" or "display: none" also changes searchbars height, so I suggest to hide it with "visibility: hidden" css code:

```css
.search-go-button {
  visibility: hidden !important;
}
```

Add it to CTRs "custom css area" or to a Stylish style.
