### ISSUE TITLE
Custom newtab-button broken with CTR 1.6.7beta7 

### ISSUE THREAD

**Issue by Vangelis66** [Aris-t2/ClassicThemeRestorer#347]
Hello Aris 

My specs first:
OS: Windows Vista SP2 32bit, WinAero enabled
Firefox: v52.1.2 ESR
CTR: latest beta, i.e. **1.6.7beta7**
CTB: latest beta, i.e. 1.5.7beta4
Stylish 2.0.7 (stable)

Through a combination of CTR+CTB+userstyles (via Stylish), I have made my Firefox to resemble IE9 (cursor hovered over newtab-button, PRTSC did not pick up cursor): 

![ntbie9](https://cloud.githubusercontent.com/assets/9669492/26531883/dc0b6e7c-43fb-11e7-9a81-ef43f31b0607.jpg)

One of my userstyles is named "newtab-button IE9 style", which turns the newtab-button appearance and behaviour into the IE9 one; the CSS code in stylish is: 
```css
/* AGENT_SHEET */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");

#new-tab-button,
.tabs-newtab-button {
  list-style-image: none !important;
}

#new-tab-button,
.tabs-newtab-button:hover {
  list-style-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAOCAYAAAD0f5bSAAABmklEQVR4XoXPv27TUBTH8fMuTLxCH4OVJ2FIVJawwQASDKQLCLUiRoTI1E3jVEld200bKaogDEWNkNKpLQzxv2uf68M5N8QKIhJX+i43+fhnw+Tq54Zu/+rrs/s0md3BKvA8j4IwRD/w/xRwIQ4Gg1L+PB++2C879+h6/9ETwWeXNwCu69LyaK6k9TML35EAGj+kFfS/zAF6vZ4hWBSkNUoGy4oBpw9IH25VUO6h2+1WCFFgUS39GO39s+SefwdwHMc8Oc9zhpxAs6bN2q9vtgHTox0tK5/9KYBt22w0o8zAQqBmiMjXfK8yg0ejM/w0vAAJOp0OlYik0oSUYqgUYV4tLu+4MDxFyx2DBO12m3RRUJrGpLKUsiWURYFyZ5DvB7jrBCCBZVmEjJI4pizlGKqMUa7kGyvkeSf41j4BCVqtlnmdOIooTiJKE15MeU2gyio0HB7j6w99kKDZbBIqRosFxXFEicA4oUzgGur3j/DVrgMv9w4AGo0G8ZEfN1Uhq/Wenr+xQYLH29tUq9ep/p9qtVr5dOcjSL8BpaBVLcaUC98AAAAASUVORK5CYII=') !important;
  padding-left: 4px !important;
  -moz-image-region: rect(-1px, 16px, 16px, 0px)!important;
}
```
That userstyle has survived many Firefox and CTR/CTB versions but, sadly, today when I upgraded from CTR 1.6.7beta6 to CTR 1.6.7beta7, _**it stopped working**_; now the newtab-button always has a grey "plus" icon, like in the screenshot below: 

![ntb-broken](https://cloud.githubusercontent.com/assets/9669492/26531975/e6bd582e-43fd-11e7-8d66-bd51196732d9.jpg)

Could you be so kind as to have a look at the breakage? 
In the interim, I have downgraded to CTR 1.6.7beta6. 

 I'll also take this opportunity to thank you in person for all your efforts during the years Australis went live; it's a sad thing that the demise of Australis and introduction of Photon will also bring the demise of CTR; being on Vista still means I won't have to tolerate either Photon nor the deprecation of XUL addons, because the highest Firefox version that would run on Vista is 52.x.x ESR...
