### ISSUE TITLE
Getting rid of "add new tab button"s border..

### ISSUE THREAD

**Issue by xevidencex** [Aris-t2/ClassicThemeRestorer#367]
Hi,

I use the australis v2 squared shape
but i don't like the border of the "add new tab button"

& i don't like the longer tabs in the alternative tab theme either..

I found a css:

.tabs-newtab-button:hover:-moz-lwtheme { border: none !important; }

But when my mouse moves away from
the button, the border steal reappears,
how can i prevent this ?

**Comment by Aris-t2** [comment]
The code only removes the border for "hovered" state and only, if you are using a lightweight theme.

Try this:

```css
#main-window #navigator-toolbox #TabsToolbar .tabs-newtab-button {
  border: none !important;
}
```
