### ISSUE TITLE
Tab seperator appearing at the end of tab' sets..

### ISSUE THREAD

**Issue by xevidencex** [Aris-t2/ClassicThemeRestorer#368]
I picked the second tab separator, a thin transparent or white with grey borders,
but on some windows, it strangely appears right after the last tab of a tab' set,

can this be fixed on a css ?

**Comment by Aris-t2** [comment]
Post a screenshot.

**Comment by xevidencex** [comment]
[IMG]https://i.imgur.com/uLA1bd2.jpg[/IMG]

**Comment by xevidencex** [comment]
https://i.imgur.com/uLA1bd2.jpg

**Comment by xevidencex** [comment]
Minor issue, if the last tab is selected, the last tab's separator doesn't appear,
but if i go have a look at one of the previous tabs without closing last tab,
that separator reappears after the last tab.

& i'd like the last tab to never show a separator after it, either the tab's selected or not.

**Comment by Aris-t2** [comment]
```css
.tabbrowser-tab[last-visible-tab]::after,
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs:not([overflow]) > .tabbrowser-tab[last-visible-tab][selected]:not([beforehovered]):not(:hover)::after,
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs:not([overflow]) > .tabbrowser-tab[last-visible-tab]:not([selected]):not([beforehovered]):not(:hover)::after {
  opacity: 0 !important;
}
```
