### ISSUE TITLE
High CPU load with vertical tabs (Tab Kit 2)

### ISSUE THREAD

**Issue by denis-martin** [Aris-t2/ClassicThemeRestorer#38]
There seems to be some CPU-load issue with FF 37.0.2 and Tab Kit 2 with vertical tabs:

https://github.com/tabkit/tabkit2/issues/85

If either of the two addons is disabled, the CPU-load goes down.

**Comment by Aris-t2** [comment]
Does this also happen with a new profile with only Tab Kit 2 and CTR installed?

In my tests there is no special impact on CPU performance with both add-ons enabled.

**Comment by denis-martin** [comment]
Yes, I used a fresh Firefox portable version with only Tab Kit 2 and CTR.

1. It only happens with vertical tabs
2. The CPU load increases with the number of tabs and ranges from ~8% to ~25% depending on the number of opened tabs (empty tabs as opened by Ctrl+N).

**Comment by denis-martin** [comment]
One more clue: When moving the mouse over the "plus" button (which adds a new tab), the highlight of the button flickers and disappears when not moving the mouse (would expect that it is always shown).

With horizontal tabs (where CPU load is not an issue), the "plus" button is different (appears like a normal tab).

**Comment by sblatnick** [comment]
I can confirm it's the combination of these two plugins.  It seems to take one core at 100%, so considering all 4 cores on my i5 processor, it looks like 25% overall.

**Comment by Aris-t2** [comment]
I found what was causing this, but I think its an error in Tab Kit 2 triggered by CTRs code.

For no explainable reason this code causes high(er) CPU load for no reason even without CTR installed (when used in Stylish for example):

.tab-background {
   -moz-margin-end: 0 !important;
   -moz-margin-start: 0 !important;
}

Next CTR beta will fix this issue by excluding the above code from vertical tabs.

By the way Firefox developer theme uses that code by default.

**Comment by denis-martin** [comment]
Yep, with CTR 1.3.2beta2 the load is back to normal, thanks!

**Comment by PikachuEXE** [comment]
Is https://github.com/Aris-t2/ClassicThemeRestorer/commit/93a0b1ed0efe422954f4d0a075165706169b089a a workaround of bug(s) of other extension(s) or actually should be fixed in this extension?

**Comment by PikachuEXE** [comment]
I might change (not in the near future) the attribute using by the extension.
So I want to understand what happens and prevents it from happening again...from my side

**Comment by Aris-t2** [comment]
```93a0b1e``` is a fix for add-ons that use vertical tabs, although I haven't seen this bug with TreeStyleTabs add-on. The rule is not required for vertical tabs anyway at least for now.

I'm not quite sure why your add-on does not like this code snipped, but as long CTR is the only add-on affected by this glitch, I would call it "fixed" for now.

To find what is causing this from your side, you have to look into your tabkit.css file. In my tests the high CPU load is caused by these two rules:

```css
#content[vertitabbar] .tabbrowser-arrowscrollbox .scrollbox-innerbox,
#TabsToolbar[vertitabbar] .tabbrowser-arrowscrollbox .scrollbox-innerbox/*[sinceFx4]*/ {
  overflow-x: hidden !important;
  overflow-y: auto !important;
}
```

```css
#TabsToolbar .tabbrowser-arrowscrollbox > .arrowscrollbox-scrollbox {
  padding-right: 0px;
}
```
