### ISSUE TITLE
how to remove/rearrange statusbar items?

### ISSUE THREAD

**Issue by FredThompsonII** [Aris-t2/ClassicThemeRestorer#392]
Early versions of FF stored the status bar configuration in localstore.rdf. It was possible to rearrange icons, remove them, and so on.

How can this be done with CTR and FF builds older than 57?

FWIW, I'm running unbranded 56.0.2...

**Comment by Aris-t2** [comment]
The toolbar configuration gets stored inside about:conbfig > browser.uiCustomization.state preference, since localstore.rdf support got dropped. Not sure, if you find everything there you are looking for, but you can install DOM Inspector and look for and classes of your stored items.

To hide them, you would need code like this in CTRs custom css area

```css
#id_of_button,
#id_of_item {
  display: none;
}
```

To rearrange items within the inaccessible status shim, you will also need custom CSS code like:

```css
#id_of_first_item {
 --moz-box-ordinal-group: 0 !important;
}

#id_of_second_item {
 --moz-box-ordinal-group: 1 !important;
}
....
```
