### ISSUE TITLE
size of check box, min-max-restore-close checkmark too small

### ISSUE THREAD

**Issue by bacounsel** [Aris-t2/ClassicThemeRestorer#398]
I'm using CTR v1.7.7.7 on Waterfox v56.2.3 on Windows 7. Having made settings, I could find no CTR preference selections that would increase the size of (i) check boxes, and (ii) the min-max-restore-close checkmark situated on the upper right-sided corner of the browser window. Currently, the check boxes in general and the close/exit checkmark are too small and I have found it hard to handle the mouse.

I would be grateful if you could please point out which selection that I could make of the preferences to enlarge their sizes, or you could possibly consider adding the necessary selections if they are not already there.

Thanks and kind regards.

**Comment by bacounsel** [comment]
I attach a graphic file relating to my question for your reference.

![checkboxes](https://user-images.githubusercontent.com/12475554/46268750-8136fa00-c566-11e8-92c6-6ac77258e477.gif)

**Comment by Aris-t2** [comment]
**"min/max/close"**
You can change the "min/max/close" button sizes on Windows 7s classic theme only (looks what you are using) by adding this code to CTRs "Custom CSS area":

```css
#titlebar-buttonbox .toolbarbutton-icon {
  width: 24px !important;
  height: 24px !important;
}

```

**"checkboxes"**
CTR tries to avoid changing web content, so there is no option to modify those. You could however right-click on one of them and select 'Inspect element'. You will find the id/class of the item(s). This opens the possibility to add the code to CTRs "Custom CSS area" like in the above example. I don't use Yahoo, so I can not tell you the exact code, but this might work (in general):

```css
input[type="checkbox"] {
  width: 24px !important;
  height: 24px !important;
}
```
