### ISSUE TITLE
Design newtabbutton

### ISSUE THREAD

**Issue by guru1d** [Aris-t2/ClassicThemeRestorer#400]
firefox 52.9.0 (64-Bit)
![grafik](https://user-images.githubusercontent.com/44544246/47614755-0f8a9700-daa5-11e8-92d6-a7a8a24498d4.png)
waterfox 56.2.3 (64-Bit)

both on Square tabs (classic)

The new tab button is very large in waterfox. I am not sure if the reason is the ClassicThemeRestorer (1.7.8) or the  Classic Toolbar Buttons (1.6.1)

Thank you for your great work!

**Comment by Aris-t2** [comment]
The icon size was changed inside browser code, but nobody seemed to be bothered.

Add this to CTRs custom CSS area.
```css
.tabs-newtab-button > .toolbarbutton-icon {
  width: 10px !important;
  height: 10px !important;
}
```
