### ISSUE TITLE
How to re-enable Legacy label in Add-ons Manager?

### ISSUE THREAD

**Issue by Wakagithub** [Aris-t2/ClassicThemeRestorer#414]
Hello. Both Waterfox Classic (right now I have 56.2.13) and the latest CTR 1.7.8.2019.07.07 no longer have the yellow `Legacy` label in the Add-ons Manager tab (`about:addons`) for non-WebEx extensions.

As suggested by a redditor, for now I re-installed the previous 1.7.8 to get it back. Is there a way to re-enable it in present CTR, perhaps via CSS in its own `Custom css code`? So that I could still have the `Legacy` label for future versions.

Thanks and more power to CTR.

**Comment by Aris-t2** [comment]
That warning seems to be gone in WF, not sure why an older CTR does make any difference on your end.

You can however recreate the legacy tag using this CSS:

```css
richlistitem[legacy="true"]::before  {
  content: "LEGACY" !important;
  display: block !important;
  background-color: #FFE900 !important;
  color: #3E2800 !important;
  padding: 4px 5px 3px !important;
  font-size: 0.9rem !important;
}
```
