### ISSUE TITLE
Small issue with FaviconizeTab extension

### ISSUE THREAD

**Issue by 1v** [Aris-t2/ClassicThemeRestorer#49]
I'm using ClassicThemeRestorer with FaviconizeTab extension and stylish style:
```
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

.tabbrowser-tabs tab[faviconized="true"][fadein="true"],
.tabbrowser-tabs tab[faviconized="true"][fadein="true"][selected] {
   min-width: 26px !important;
   margin-left: -1px;
}

.tabbrowser-tabs tab[faviconized="true"][fadein="true"] .tab-icon {
   margin-right: -7px;
}
```
to achieve something like this:
![](http://img-fotki.yandex.ru/get/6406/203537249.13/0_122175_337045fb_orig.png)
In new ClassicThemeRestorer version I changed style to:
```
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

.tabbrowser-tabs tab[faviconized="true"][fadein="true"],
.tabbrowser-tabs tab[faviconized="true"][fadein="true"][selected] {
   min-width: 26px !important;
   margin-left: -1px !important;
}

.tabbrowser-tabs tab[faviconized="true"] .tab-icon {
   margin-right: -5px !important;
   margin-left: -5px !important;
}
```
and all remained same except conneting and loading icons:
![](http://img-fotki.yandex.ru/get/5/203537249.13/0_122174_5530f56e_orig.png)
they've moved 5px to the left. And I can't realise wich style in new version caused this.

**Comment by Aris-t2** [comment]
I will adjust tab throbber position for faviconize tabs on next (beta) build.

You could try to use Stylish add-on and also replace
.tabbrowser-tabs tab[faviconized="true"] with  #tabbrowser-tabs .tabbrowser-tab[faviconized="true"].

You can use now
```css
/*AGENT_SHEET*/
* #tabbrowser-tabs .tabbrowser-tab[faviconized="true"][fadein="true"],
* #tabbrowser-tabs .tabbrowser-tab[faviconized="true"][selected] {
  min-width: 26px !important;
  margin-left: -1px !important;
}
* #tabbrowser-tabs .tabbrowser-tab[faviconized="true"] .tab-throbber,
* #tabbrowser-tabs .tabbrowser-tab[faviconized="true"] .tab-icon-image {
  margin-right: -5px !important;
  margin-left: -3px !important;
}
* #tabbrowser-tabs .tabbrowser-tab[faviconized="true"] {
  max-width: 22px !important;
}
```

After next CTR update you have to change the -5px to -3px.
